name: Push to Int

on:
  push:
    branches: [ development ]
    
jobs:
  build:

    runs-on: windows-2019

    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1   
      with:
        format: 'json'
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: git diff --name-status origin/main > branch.diff
    - run: npm install
    - run: npm run build
    - run: node .\packager\solutionGeneration.js
      env:
        all_comp: ${{ steps.files.outputs.all }}
    - name: Build Solution
      run: powershell .\packager\import_artifacts.ps1
    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: 'https://e2poc.crm9.dynamics.com/'
        user-name: 'christopher.nichols@e2poc.onmicrosoft.com'
        password-secret: ${{ secrets.PASSWORD }}
        solution-file: packager/import.zip
        force-overwrite: true
        publish-changes: true
    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: import artifacts 
        path: |
          artifacts
